"""
Interactive visualization tool for the SNA-QDL protocol.

This script provides an interactive simulation and visualization framework
to study statistical properties of the density matrix arising in the SNA-QDL
protocol. The program allows the user to configure the main parameters of the 
model, including the qudit dimension (d), the number of transmitted symbols 
(n), and the leakage rate (λ). From these parameters, the effective number 
of private symbols and the range of secret-key sizes (κ) are computed.

For each value of κ, the script evaluates the logarithmic magnitude of
density matrix elements ρ(a,b) generated by the protocol under random
instances of the encoding matrix. The program then visualizes two main
aspects of the resulting distribution:

    - A heatmap representing a block of the density matrix in logarithmic scale.
    - A histogram showing the statistical distribution of non-zero
      logarithmic amplitudes log|ρ(a,b)|.

The visualization can be executed either in automatic animation mode,
where frames advance sequentially in time, or in manual mode, allowing
navigation through different κ values using control buttons. This enables
the study of how the density matrix structure evolves as the key length
increases and how key cancellation progressively sparsifies the matrix.

The tool is intended for exploratory analysis and qualitative understanding
of the locking behavior and statistical structure induced by the SNA-QDL
protocol, complementing the numerical benchmarks and theoretical results
presented in the associated research.

Dependencies: numpy, matplotlib
Authors: Yauset Cabrera-Aparicio, Jorge García-Díaz, Pino Caballero-Gil (2026)
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.animation as animation
from matplotlib.widgets import TextBox, Button, RadioButtons
from matplotlib.colors import LinearSegmentedColormap
import math

BG        = "#F7F9FC"
PANEL_BG  = "#FFFFFF"
GRID_COL  = "#DDE3ED"
TEXT_DARK = "#1A2340"
TEXT_MID  = "#4A5568"
ACCENT    = "#1E3A8A"
SPINE_COL = "#CBD5E1"

plt.rcParams.update({
    "figure.facecolor":  BG,        "axes.facecolor":    PANEL_BG,
    "axes.edgecolor":    SPINE_COL, "axes.labelcolor":   TEXT_DARK,
    "axes.titlecolor":   TEXT_DARK, "axes.spines.top":   False,
    "axes.spines.right": False,     "xtick.color":       TEXT_MID,
    "ytick.color":       TEXT_MID,  "xtick.labelsize":   9,
    "ytick.labelsize":   9,         "font.family":       "DejaVu Sans",
    "grid.color":        GRID_COL,  "grid.linewidth":    0.8,
    "text.usetex":       False,
})

params = {"d": None, "n": None, "lam": None, "ready": False, "mode": "auto"}


#  Configuration window

def launch_input_screen():
    fig_in = plt.figure(figsize=(7.5, 6.5), facecolor=BG)
    fig_in.canvas.manager.set_window_title("SNA-QDL — Parameters Input")

    fig_in.text(0.5, 0.91, "Configuration  SNA-QDL Simulation",
                ha="center", fontsize=14, fontweight="bold", color=TEXT_DARK)
    fig_in.text(0.5, 0.855, "Introduce the parameters for the simulation",
                ha="center", fontsize=10, color=TEXT_MID)
    fig_in.add_artist(plt.Line2D([0.1, 0.9], [0.838, 0.838],
                                  transform=fig_in.transFigure,
                                  color=SPINE_COL, linewidth=1.0))

    ax_d   = fig_in.add_axes([0.55, 0.72, 0.25, 0.07])
    ax_n   = fig_in.add_axes([0.55, 0.60, 0.25, 0.07])
    ax_lam = fig_in.add_axes([0.55, 0.48, 0.25, 0.07])

    tb_d   = TextBox(ax_d,   "(qudit dimension)  ", initial="8",    color=PANEL_BG, hovercolor="#EFF6FF")
    tb_n   = TextBox(ax_n,   "(number of qubits)  ", initial="300", color=PANEL_BG, hovercolor="#EFF6FF")
    tb_lam = TextBox(ax_lam, "(leakage rate)  ",     initial="0.2", color=PANEL_BG, hovercolor="#EFF6FF")

    for tb in [tb_d, tb_n, tb_lam]:
        tb.label.set_color(TEXT_MID); tb.label.set_fontsize(9)
        tb.label.set_style("italic"); tb.label.set_horizontalalignment('right')

    for y, label in zip([0.755, 0.635, 0.515], ["$d$", "$n$", r"$\lambda$"]):
        fig_in.text(0.18, y, label, ha="center", fontsize=14,
                    fontweight="bold", color=ACCENT)

    fig_in.text(0.5, 0.38,
                r"In the simulation, $\kappa$ will vary from $1$ to $\lceil 5\,\log_d(n) \rceil$",
                ha="center", fontsize=10, color=TEXT_MID, style="italic")

    fig_in.add_artist(plt.Line2D([0.1, 0.9], [0.355, 0.355],
                                  transform=fig_in.transFigure,
                                  color=SPINE_COL, linewidth=0.7))
    fig_in.text(0.5, 0.325, "Visualization Mode",
                ha="center", fontsize=10, fontweight="bold", color=TEXT_DARK)

    ax_radio = fig_in.add_axes([0.28, 0.195, 0.44, 0.115], facecolor="#F0F4FA")
    radio = RadioButtons(ax_radio,
                         ("Auto (timed animation)", "Manual (arrow buttons)"),
                         active=0, activecolor=ACCENT)
    for lbl in radio.labels:
        lbl.set_fontsize(9.5); lbl.set_color(TEXT_DARK)

    mode_desc = fig_in.text(
        0.5, 0.175, "Frames advance automatically every 1.4 s",
        ha="center", fontsize=8.5, color=TEXT_MID, style="italic")

    def on_mode_change(label):
        if "Auto" in label:
            mode_desc.set_text("Frames advance automatically every 1.4 s")
            params["mode"] = "auto"
        else:
            mode_desc.set_text(r"Use ◀ / ▶ buttons to navigate between $\kappa$ values")
            params["mode"] = "manual"
        fig_in.canvas.draw()

    radio.on_clicked(on_mode_change)

    ax_btn = fig_in.add_axes([0.35, 0.055, 0.30, 0.09])
    btn = Button(ax_btn, "  ▶  Run", color=ACCENT, hovercolor="#2563EB")
    btn.label.set_color("white"); btn.label.set_fontsize(11); btn.label.set_fontweight("bold")

    err_txt = fig_in.text(0.5, 0.022, "", ha="center", fontsize=9, color="#DC2626")

    def on_submit(_):
        try:
            d_val   = int(tb_d.text.strip())
            n_val   = int(tb_n.text.strip())
            lam_val = float(tb_lam.text.strip())
            if d_val < 2 or n_val < 2 or not (0 < lam_val < 1):
                raise ValueError
            params["d"] = d_val; params["n"] = n_val; params["lam"] = lam_val
            params["ready"] = True
            plt.close(fig_in)
        except ValueError:
            err_txt.set_text(r"⚠ Invalid values. Check $d \geq 2$, $n \geq 2$, $0 < \lambda < 1$")
            fig_in.canvas.draw()

    btn.on_clicked(on_submit)
    plt.show()

launch_input_screen()
if not params["ready"]:
    raise SystemExit("Run cancelled.")

d           = params["d"]
n           = params["n"]
lambda_leak = params["lam"]
viz_mode    = params["mode"]
kappa_max   = math.ceil(5 * math.log(n) / math.log(d))
kappa_list  = list(range(1, kappa_max + 1))

print(f"\n► d={d}, n={n}, λ={lambda_leak}, mode={viz_mode}")
print(f"► κ from 1 to {kappa_max}  ({len(kappa_list)} frames)\n")

block_size = 100
samples    = 5000

def compute_frame(kappa):
    k_leak = int(round(lambda_leak * n))
    n_priv = max(n - k_leak, 1)

    F = np.random.randint(d, size=(n_priv, kappa))
    log_norm = -n_priv * math.log(d)

    def log_rho_element(a, b):
        diff = (a - b) % d
        for l in range(kappa):
            if int(np.dot(F[:, l], diff)) % d != 0:
                return -np.inf
        return log_norm

    def idx_to_vec(i, length):
        v = np.empty(length, dtype=np.int8)
        for j in range(length):
            v[j] = i % d; i //= d
        return v

    sz = min(block_size, d ** min(n_priv, 6))
    block_log = np.full((sz, sz), -np.inf)
    vecs = [idx_to_vec(i, n_priv) for i in range(sz)]
    for i in range(sz):
        for j in range(sz):
            block_log[i, j] = log_rho_element(vecs[i], vecs[j])

    log_vals = np.array([
        log_rho_element(
            np.random.randint(d, size=n_priv, dtype=np.int8),
            np.random.randint(d, size=n_priv, dtype=np.int8)
        ) for _ in range(samples)
    ])
    frac_nonzero = np.sum(np.isfinite(log_vals)) / samples
    return block_log, log_vals, n_priv, frac_nonzero, log_norm


_metal_colors = [
    (0.91, 0.95, 0.99),   # near-white ice
    (0.73, 0.84, 0.95),   # pale steel blue
    (0.48, 0.67, 0.87),   # light cobalt
    (0.27, 0.48, 0.76),   # mid steel
    (0.14, 0.28, 0.60),   # deep cobalt
    (0.07, 0.14, 0.36),   # dark indigo steel
    (0.03, 0.06, 0.17),   # midnight navy
]
metallic_cmap = LinearSegmentedColormap.from_list("metallic_inv", _metal_colors, N=512)

CTRL_Y = 0.045
BTN_Y  = 0.005
BAR_H  = 0.025
BTN_H  = 0.052
BTN_W  = 0.07

fig = plt.figure(figsize=(14, 7.2), facecolor=BG)
fig.canvas.manager.set_window_title("SNA-QDL — Animation κ")

gs = gridspec.GridSpec(1, 2, left=0.07, right=0.96,
                       top=0.78, bottom=0.16, wspace=0.38)
ax_img  = fig.add_subplot(gs[0])
ax_hist = fig.add_subplot(gs[1])

title_txt = fig.suptitle("", fontsize=13, fontweight="bold", color=TEXT_DARK, y=0.97)
sub_txt   = fig.text(0.5, 0.905, "", ha="center", fontsize=10, color=TEXT_MID)
fig.add_artist(plt.Line2D([0.07, 0.96], [0.888, 0.888],
                           transform=fig.transFigure, color=SPINE_COL, linewidth=1.0))

ax_prog = fig.add_axes([0.10, CTRL_Y, 0.80, BAR_H])
ax_prog.set_xlim(0, len(kappa_list))
ax_prog.set_ylim(0, 1)
ax_prog.set_facecolor(GRID_COL)
ax_prog.axis("off")
prog_bar = ax_prog.barh(0.5, 0, height=1.0, color=ACCENT, align="center")
prog_txt = ax_prog.text(
    len(kappa_list) / 2, 0.5, "",
    ha="center", va="center",
    fontsize=8.5, color="white", fontweight="bold")

ax_prev = fig.add_axes([0.435, BTN_Y, BTN_W, BTN_H])
ax_next = fig.add_axes([0.515, BTN_Y, BTN_W, BTN_H])
btn_prev = Button(ax_prev, "◀  Prev", color="#E2E8F0", hovercolor="#CBD5E1")
btn_next = Button(ax_next, "Next  ▶", color=ACCENT,    hovercolor="#2563EB")
for b, col in [(btn_prev, TEXT_DARK), (btn_next, "white")]:
    b.label.set_fontsize(9); b.label.set_color(col)

dummy = np.zeros((block_size, block_size))
im = ax_img.imshow(dummy, cmap=metallic_cmap, origin="upper",
                   aspect="auto", interpolation="nearest")

cbar = fig.colorbar(im, ax=ax_img, fraction=0.046, pad=0.03)
cbar.set_label(r"$\log|\rho|$", fontsize=10, color=TEXT_DARK)
cbar.ax.yaxis.set_tick_params(color=TEXT_MID, labelsize=8)
cbar.outline.set_edgecolor(SPINE_COL)

ax_img.set_xlabel("Column index", fontsize=10, labelpad=6, color=TEXT_DARK)
ax_img.set_ylabel("Row index",    fontsize=10, labelpad=6, color=TEXT_DARK)
ax_img.tick_params(length=0)

def render_frame(frame_idx):
    kappa = kappa_list[frame_idx]
    block_log, log_vals, n_priv, frac_nz, log_norm = compute_frame(kappa)

    finite_vals = block_log[np.isfinite(block_log)]
    v_min = finite_vals.min() if len(finite_vals) > 0 else -1
    v_max = finite_vals.max() if len(finite_vals) > 0 else 0
    display = np.where(np.isfinite(block_log), block_log, v_min - 1)

    span  = max(v_max - (v_min - 1), 1e-12)
    norm_d = np.clip((display - (v_min - 1)) / span, 0, 1)

    rows, cols = norm_d.shape
    rr, cc = np.meshgrid(np.linspace(0, 1, rows),
                          np.linspace(0, 1, cols), indexing='ij')

    highlight  = 0.07 * np.exp(-3.0 * (rr + cc))
    sheen      = 0.05 * np.exp(-12.0 * (rr - cc) ** 2)
    shaded      = np.clip(norm_d + highlight + sheen, 0, 1)
    shaded_data = shaded * span + (v_min - 1)

    im.set_data(shaded_data)
    im.set_clim(vmin=v_min - 1, vmax=v_max + 1e-12)
    ax_img.set_title(
        r"$\log|\rho|$ map  —  $\kappa = $" + str(kappa),
        fontsize=11, fontweight="bold", color=ACCENT, pad=8)
    cbar.set_label(r"$\log|\rho(a,b)|$", fontsize=10, color=TEXT_DARK)

    # ── Histogram 
    ax_hist.cla()
    ax_hist.set_facecolor(PANEL_BG)
    for sp in ["top", "right"]:
        ax_hist.spines[sp].set_visible(False)
    for sp in ["left", "bottom"]:
        ax_hist.spines[sp].set_edgecolor(SPINE_COL)

    finite_log = log_vals[np.isfinite(log_vals)]
    pct_zero   = (1 - frac_nz) * 100

    if len(finite_log) > 0:
        ax_hist.hist(
            finite_log, bins=40,
            color="#60A5FA", edgecolor=PANEL_BG, linewidth=0.4, alpha=0.88,
            label=rf"$\rho_{{ab}} \neq 0$  $({frac_nz*100:.1f}\%)$")
        mean_v = finite_log.mean()
        ax_hist.axvline(
            mean_v, color=ACCENT, linewidth=1.8, linestyle="--",
            label=rf"$\mu = {mean_v:.2f}$")
        ax_hist.axvline(
            log_norm, color="#DC2626", linewidth=1.4, linestyle=":", alpha=0.8,
            label=rf"$\log(d^{{-n'}}) = {log_norm:.1f}$")
        ax_hist.legend(fontsize=8.5, frameon=True,
                       edgecolor=SPINE_COL, framealpha=0.95)
    else:
        ax_hist.text(
            0.5, 0.5,
            rf"All elements $= 0$" + "\n" + rf"($\kappa = {kappa}$, cancellation $= {pct_zero:.1f}\%$)",
            ha="center", va="center", transform=ax_hist.transAxes,
            fontsize=10, color=TEXT_MID)

    ax_hist.text(
        0.02, 0.97,
        rf"${pct_zero:.1f}\%$ null elements" + "\n" + r"(key cancellation)",
        transform=ax_hist.transAxes, fontsize=8, color=TEXT_MID,
        va="top", ha="left",
        bbox=dict(boxstyle="round,pad=0.3", facecolor=BG,
                  edgecolor=SPINE_COL, linewidth=0.7))

    ax_hist.set_title(
        r"Distribution of $\log|\rho_{ab}|$  —  $\kappa = $" + str(kappa),
        fontsize=11, fontweight="bold", color=ACCENT, pad=8)
    ax_hist.set_xlabel(
        r"$\log|\rho(a,b)|$  (non-null elements)",
        fontsize=10, labelpad=6, color=TEXT_DARK)
    ax_hist.set_ylabel("Frequency", fontsize=10, labelpad=6, color=TEXT_DARK)
    ax_hist.yaxis.grid(True, linestyle="--", alpha=0.7)
    ax_hist.set_axisbelow(True)
    ax_hist.tick_params(length=0)

    title_txt.set_text(
        r"Density Matrix Analysis  SNA-QDL  —  Logarithmic Scale")
    sub_txt.set_text(
        rf"$d = {d}$   ·   $n = {n}$   ·   $\lambda = {lambda_leak}$"
        rf"   ·   $n' = {n_priv}$"
        rf"   ·   $\kappa = {kappa} \,/\, {kappa_max}$"
    )
    prog_bar[0].set_width(frame_idx + 1)
    prog_txt.set_text(rf"$\kappa = {kappa}$  ({(frame_idx+1)/len(kappa_list)*100:.0f}%)")

    fig.canvas.draw_idle()
    return [im]


#  Auto mode
if viz_mode == "auto":
    ax_prev.set_visible(False)
    ax_next.set_visible(False)

    ani = animation.FuncAnimation(
        fig, render_frame,
        frames=len(kappa_list),
        interval=1400,
        repeat=False,
        blit=False
    )

#  Manual mode
else:
    state = {"frame": 0}

    def go_to(idx):
        idx = max(0, min(idx, len(kappa_list) - 1))
        state["frame"] = idx
        render_frame(idx)

    render_frame(0)
    btn_prev.on_clicked(lambda _: go_to(state["frame"] - 1))
    btn_next.on_clicked(lambda _: go_to(state["frame"] + 1))

plt.show()